package com.nnxy.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.nnxy.entity.User;

import com.nnxy.entity.Account;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACCOUNT".
*/
public class AccountDao extends AbstractDao<Account, Long> {

    public static final String TABLENAME = "ACCOUNT";

    /**
     * Properties of entity Account.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Acc_id = new Property(0, Long.class, "acc_id", true, "ACC_ID");
        public final static Property Address = new Property(1, String.class, "address", false, "ADDRESS");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property Money = new Property(3, double.class, "money", false, "MONEY");
        public final static Property Zw_leibie = new Property(4, String.class, "zw_leibie", false, "ZW_LEIBIE");
        public final static Property Leibie = new Property(5, String.class, "leibie", false, "LEIBIE");
        public final static Property Note = new Property(6, String.class, "note", false, "NOTE");
        public final static Property User_id = new Property(7, Long.class, "user_id", false, "USER_ID");
    };

    private DaoSession daoSession;


    public AccountDao(DaoConfig config) {
        super(config);
    }
    
    public AccountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACCOUNT\" (" + //
                "\"ACC_ID\" INTEGER PRIMARY KEY ," + // 0: acc_id
                "\"ADDRESS\" TEXT NOT NULL ," + // 1: address
                "\"DATE\" TEXT NOT NULL ," + // 2: date
                "\"MONEY\" REAL NOT NULL ," + // 3: money
                "\"ZW_LEIBIE\" TEXT NOT NULL ," + // 4: zw_leibie
                "\"LEIBIE\" TEXT NOT NULL ," + // 5: leibie
                "\"NOTE\" TEXT NOT NULL ," + // 6: note
                "\"USER_ID\" INTEGER);"); // 7: user_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACCOUNT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Account entity) {
        stmt.clearBindings();
 
        Long acc_id = entity.getAcc_id();
        if (acc_id != null) {
            stmt.bindLong(1, acc_id);
        }
        stmt.bindString(2, entity.getAddress());
        stmt.bindString(3, entity.getDate());
        stmt.bindDouble(4, entity.getMoney());
        stmt.bindString(5, entity.getZw_leibie());
        stmt.bindString(6, entity.getLeibie());
        stmt.bindString(7, entity.getNote());
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(8, user_id);
        }
    }

    @Override
    protected void attachEntity(Account entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Account readEntity(Cursor cursor, int offset) {
        Account entity = new Account( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // acc_id
            cursor.getString(offset + 1), // address
            cursor.getString(offset + 2), // date
            cursor.getDouble(offset + 3), // money
            cursor.getString(offset + 4), // zw_leibie
            cursor.getString(offset + 5), // leibie
            cursor.getString(offset + 6), // note
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // user_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Account entity, int offset) {
        entity.setAcc_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAddress(cursor.getString(offset + 1));
        entity.setDate(cursor.getString(offset + 2));
        entity.setMoney(cursor.getDouble(offset + 3));
        entity.setZw_leibie(cursor.getString(offset + 4));
        entity.setLeibie(cursor.getString(offset + 5));
        entity.setNote(cursor.getString(offset + 6));
        entity.setUser_id(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Account entity, long rowId) {
        entity.setAcc_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Account entity) {
        if(entity != null) {
            return entity.getAcc_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM ACCOUNT T");
            builder.append(" LEFT JOIN USER T0 ON T.\"USER_ID\"=T0.\"USER_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Account loadCurrentDeep(Cursor cursor, boolean lock) {
        Account entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setUser(user);

        return entity;    
    }

    public Account loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Account> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Account> list = new ArrayList<Account>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Account> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Account> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
